<?php

return [
    'sections' => [
        'attendance' => [
            'label' => 'Attendance',
            'description' => 'Attendance operations, approvals, schedules, and reporting.',
        ],
        'finance' => [
            'label' => 'Finance',
            'description' => 'Payroll, reimbursements, and cash advance workflows.',
        ],
        'master_data' => [
            'label' => 'Master Data',
            'description' => 'Employee records, organization references, and operational directories.',
        ],
        'operations' => [
            'label' => 'Operations',
            'description' => 'Client, project, task, checklist, and field work operations.',
        ],
        'system' => [
            'label' => 'System',
            'description' => 'Settings, logs, import/export, and access management.',
        ],
    ],

    'modules' => [
        'dashboard' => [
            'section' => 'system',
            'label' => 'Dashboard',
            'description' => 'Admin landing page and summary cards.',
            'route_names' => ['admin.dashboard'],
            'existing_authorization' => 'Gate:viewAdminDashboard',
            'menu_location' => 'Admin navigation > Dashboard',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.dashboard.view', 'label' => 'View'],
            ],
        ],
        'command_center' => [
            'section' => 'operations',
            'label' => 'Command Center',
            'description' => 'Cross-module cockpit for approvals, HR tasks, operations, sales, and invoice risk.',
            'route_names' => ['admin.command-center'],
            'existing_authorization' => 'Gate:viewCommandCenter + CommandCenterService',
            'menu_location' => 'Admin navigation > Command Center',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.command_center.view', 'label' => 'View'],
            ],
        ],
        'attendances' => [
            'section' => 'attendance',
            'label' => 'Daily Attendance',
            'description' => 'Review attendance records and reports.',
            'route_names' => ['admin.attendances', 'admin.attendances.report'],
            'existing_authorization' => 'Policy:Attendance@viewAdminAny + route can:viewAttendanceReports',
            'menu_location' => 'Admin navigation > Attendance > Daily Attendance',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.attendances.view', 'label' => 'View'],
                'report' => ['permission' => 'admin.attendances.report', 'label' => 'Report'],
                'export' => ['permission' => 'admin.attendances.export', 'label' => 'Export'],
            ],
        ],
        'attendance_corrections' => [
            'section' => 'attendance',
            'label' => 'Corrections',
            'description' => 'Review and process attendance correction requests.',
            'route_names' => ['admin.attendance-corrections'],
            'existing_authorization' => 'Policy:AttendanceCorrection@viewAdminAny/approve',
            'menu_location' => 'Admin navigation > Attendance > Corrections',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.attendance_corrections.view', 'label' => 'View'],
                'approve' => ['permission' => 'admin.attendance_corrections.approve', 'label' => 'Approve'],
            ],
        ],
        'wfh_requests' => [
            'section' => 'attendance',
            'label' => 'WFH Requests',
            'description' => 'Review work-from-home requests from employees.',
            'route_names' => ['approvals'],
            'existing_authorization' => 'Gate:reviewSubordinateRequests/manageWfhRequests + Policy:WorkFromHomeRequest',
            'menu_location' => 'User navigation > Team Approvals > WFH',
            'surface' => 'user',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.wfh_requests.manage', 'label' => 'Manage'],
            ],
        ],
        'leave_approvals' => [
            'section' => 'attendance',
            'label' => 'Approvals',
            'description' => 'Process leave and attendance approval queues.',
            'route_names' => ['admin.leaves'],
            'existing_authorization' => 'Gate:manageLeaveApprovals',
            'menu_location' => 'Admin navigation > Attendance > Approvals',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'approve' => ['permission' => 'admin.leave_approvals.approve', 'label' => 'Approve'],
            ],
        ],
        'shift_swaps' => [
            'section' => 'attendance',
            'label' => 'Shift Swap Approvals',
            'description' => 'Review and approve employee shift swap and schedule change requests.',
            'route_names' => ['admin.shift-swaps'],
            'existing_authorization' => 'Gate:manageShiftSwapApprovals',
            'menu_location' => 'Admin navigation > Attendance > Shift Swap Approvals',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'approve' => ['permission' => 'admin.shift_swaps.approve', 'label' => 'Approve'],
            ],
        ],
        'overtime' => [
            'section' => 'attendance',
            'label' => 'Overtime',
            'description' => 'Manage overtime submissions and follow-up.',
            'route_names' => ['admin.overtime'],
            'existing_authorization' => 'Gate:manageOvertime',
            'menu_location' => 'Admin navigation > Attendance > Overtime',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.overtime.manage', 'label' => 'Manage'],
            ],
        ],
        'schedules' => [
            'section' => 'attendance',
            'label' => 'Schedules (Roster)',
            'description' => 'Manage roster and shift schedules.',
            'route_names' => ['admin.schedules'],
            'existing_authorization' => 'Gate:manageSchedules',
            'menu_location' => 'Admin navigation > Attendance > Schedules (Roster)',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.schedules.manage', 'label' => 'Manage'],
            ],
        ],
        'analytics' => [
            'section' => 'attendance',
            'label' => 'Analytics',
            'description' => 'Attendance analytics and operational trends.',
            'route_names' => ['admin.analytics'],
            'existing_authorization' => 'Gate:viewAnalyticsDashboard',
            'menu_location' => 'Admin navigation > Attendance > Analytics',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.analytics.view', 'label' => 'View'],
            ],
        ],
        'holidays' => [
            'section' => 'attendance',
            'label' => 'Holidays',
            'description' => 'Manage holiday calendars.',
            'route_names' => ['admin.holidays'],
            'existing_authorization' => 'Gate:manageHolidays + Policy:Holiday',
            'menu_location' => 'Admin navigation > Attendance > Holidays',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.holidays.manage', 'label' => 'Manage'],
            ],
        ],
        'announcements' => [
            'section' => 'attendance',
            'label' => 'Announcements',
            'description' => 'Publish and maintain internal announcements.',
            'route_names' => ['admin.announcements'],
            'existing_authorization' => 'Gate:manageAnnouncements + Policy:Announcement',
            'menu_location' => 'Admin navigation > Attendance > Announcements',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.announcements.manage', 'label' => 'Manage'],
            ],
        ],
        'payroll' => [
            'section' => 'finance',
            'label' => 'Payroll',
            'description' => 'Open payroll records and salary processing views.',
            'route_names' => ['admin.payrolls'],
            'existing_authorization' => 'Policy:Payroll@viewAdminAny',
            'menu_location' => 'Admin navigation > Finance > Payroll',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.payroll.view', 'label' => 'View'],
            ],
        ],
        'reimbursements' => [
            'section' => 'finance',
            'label' => 'Reimbursements',
            'description' => 'Review employee reimbursement requests.',
            'route_names' => ['admin.reimbursements'],
            'existing_authorization' => 'Policy:Reimbursement@viewAdminAny/approve',
            'menu_location' => 'Admin navigation > Finance > Reimbursements',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.reimbursements.view', 'label' => 'View'],
                'approve' => ['permission' => 'admin.reimbursements.approve', 'label' => 'Approve'],
            ],
        ],
        'cash_advances' => [
            'section' => 'finance',
            'label' => 'Manage Kasbon',
            'description' => 'Manage cash advance requests and finance follow-up.',
            'route_names' => ['admin.manage-kasbon'],
            'existing_authorization' => 'Gate:manageCashAdvances + Policy:CashAdvance',
            'menu_location' => 'Admin navigation > Finance > Manage Kasbon',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'manage' => ['permission' => 'admin.cash_advances.manage', 'label' => 'Manage'],
            ],
        ],
        'payroll_settings' => [
            'section' => 'finance',
            'label' => 'Payroll Settings',
            'description' => 'Configure payroll rules and component settings.',
            'route_names' => ['admin.payroll.settings'],
            'existing_authorization' => 'Policy:Payroll@viewAdminAny',
            'menu_location' => 'Admin navigation > Finance > Payroll Settings',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'manage' => ['permission' => 'admin.payroll_settings.manage', 'label' => 'Manage'],
            ],
        ],
        'employees' => [
            'section' => 'master_data',
            'label' => 'Employees',
            'description' => 'Manage employee directory records, lifecycle status, and account deletion approvals.',
            'route_names' => ['admin.employees'],
            'existing_authorization' => 'Gate:viewEmployees + Gate:manageUserRecord',
            'menu_location' => 'Admin navigation > Master Data > Employees',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.employees.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.employees.manage', 'label' => 'Manage'],
                'manage_status' => ['permission' => 'admin.employees.manage_status', 'label' => 'Manage employment status'],
                'approve_account_deletion' => ['permission' => 'admin.employees.approve_account_deletion', 'label' => 'Approve account deletion'],
            ],
        ],
        'hr_checklists' => [
            'section' => 'master_data',
            'label' => 'HR Checklists',
            'description' => 'Run onboarding and offboarding checklist cases.',
            'route_names' => ['admin.hr-checklists'],
            'existing_authorization' => 'Policy:HrChecklistCase@viewAny/create/update + Gate:viewHrChecklists/manageHrChecklists',
            'menu_location' => 'Admin navigation > Master Data > HR Checklists',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.hr_checklists.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.hr_checklists.manage', 'label' => 'Manage'],
            ],
        ],
        'document_requests' => [
            'section' => 'master_data',
            'label' => 'Document Requests',
            'description' => 'Review employee document requests.',
            'route_names' => ['admin.document-requests'],
            'existing_authorization' => 'Policy:EmployeeDocumentRequest@viewAdminAny/fulfill',
            'menu_location' => 'Admin navigation > Master Data > Document Requests',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.document_requests.view', 'label' => 'View'],
                'request' => ['permission' => 'admin.document_requests.request', 'label' => 'Request from employee'],
                'generate' => ['permission' => 'admin.document_requests.generate', 'label' => 'Generate documents'],
                'templates' => ['permission' => 'admin.document_requests.templates', 'label' => 'Manage templates'],
                'fulfill' => ['permission' => 'admin.document_requests.fulfill', 'label' => 'Fulfill'],
            ],
        ],
        'appraisals' => [
            'section' => 'master_data',
            'label' => 'Performance Appraisals',
            'description' => 'View, manage, and calibrate performance appraisals.',
            'route_names' => ['admin.appraisals'],
            'existing_authorization' => 'Policy:Appraisal@viewAdminAny/manage/calibrate',
            'menu_location' => 'Admin navigation > Master Data > Performance Appraisals',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.appraisals.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.appraisals.manage', 'label' => 'Manage'],
                'calibrate' => ['permission' => 'admin.appraisals.calibrate', 'label' => 'Calibrate'],
            ],
        ],
        'assets' => [
            'section' => 'master_data',
            'label' => 'Company Assets',
            'description' => 'Review company asset assignments.',
            'route_names' => ['admin.assets'],
            'existing_authorization' => 'Policy:CompanyAsset@viewAdminAny',
            'menu_location' => 'Admin navigation > Master Data > Company Assets',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.assets.view', 'label' => 'View'],
            ],
        ],
        'barcodes' => [
            'section' => 'master_data',
            'label' => 'Barcode Locations',
            'description' => 'Manage barcode locations and related downloads.',
            'route_names' => ['admin.barcodes', 'admin.barcodes.create', 'admin.barcodes.store', 'admin.barcodes.show', 'admin.barcodes.edit', 'admin.barcodes.update', 'admin.barcodes.regenerate-secret', 'admin.barcodes.dynamic-display', 'admin.barcodes.dynamic-token', 'admin.barcodes.downloadall', 'admin.barcodes.download'],
            'existing_authorization' => 'Gate:manageBarcodes',
            'menu_location' => 'Admin navigation > Master Data > Barcode Locations',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.barcodes.manage', 'label' => 'Manage'],
            ],
        ],
        'divisions' => [
            'section' => 'master_data',
            'label' => 'Divisions',
            'description' => 'Manage division reference data.',
            'route_names' => ['admin.masters.division'],
            'existing_authorization' => 'Gate:manageMasterData',
            'menu_location' => 'Admin navigation > Master Data > Divisions',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.divisions.manage', 'label' => 'Manage'],
            ],
        ],
        'job_titles' => [
            'section' => 'master_data',
            'label' => 'Job Titles',
            'description' => 'Manage job title reference data.',
            'route_names' => ['admin.masters.job-title'],
            'existing_authorization' => 'Gate:manageMasterData',
            'menu_location' => 'Admin navigation > Master Data > Job Titles',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.job_titles.manage', 'label' => 'Manage'],
            ],
        ],
        'educations' => [
            'section' => 'master_data',
            'label' => 'Education Levels',
            'description' => 'Manage education level reference data.',
            'route_names' => ['admin.masters.education'],
            'existing_authorization' => 'Gate:manageMasterData',
            'menu_location' => 'Admin navigation > Master Data > Education Levels',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.educations.manage', 'label' => 'Manage'],
            ],
        ],
        'shifts' => [
            'section' => 'master_data',
            'label' => 'Shifts',
            'description' => 'Manage shift reference data.',
            'route_names' => ['admin.masters.shift'],
            'existing_authorization' => 'Gate:manageMasterData',
            'menu_location' => 'Admin navigation > Master Data > Shifts',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.shifts.manage', 'label' => 'Manage'],
            ],
        ],
        'leave_types' => [
            'section' => 'master_data',
            'label' => 'Leave Types',
            'description' => 'Manage annual leave, sick leave, and special leave request types.',
            'route_names' => ['admin.masters.leave-types'],
            'existing_authorization' => 'Gate:manageLeaveTypes',
            'menu_location' => 'Admin navigation > Master Data > Leave Types',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.leave_types.manage', 'label' => 'Manage'],
            ],
        ],
        'leave_entitlements' => [
            'section' => 'master_data',
            'label' => 'Leave Entitlements',
            'description' => 'Manage annual leave allocation, carry-over, and expiry per employee.',
            'route_names' => ['admin.masters.leave-entitlements'],
            'existing_authorization' => 'Gate:manageLeaveEntitlements',
            'menu_location' => 'Admin navigation > Master Data > Leave Entitlements',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.leave_entitlements.manage', 'label' => 'Manage'],
            ],
        ],
        'admin_accounts' => [
            'section' => 'master_data',
            'label' => 'Administrators',
            'description' => 'Manage administrator and superadmin accounts and access groups.',
            'route_names' => ['admin.masters.admin'],
            'existing_authorization' => 'Gate:viewAdminAccounts + Gate:manageUserRecord + explicit superadmin account permissions',
            'menu_location' => 'Admin navigation > Master Data > Administrators',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.admin_accounts.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.admin_accounts.manage', 'label' => 'Manage'],
                'superadmin_view' => ['permission' => 'admin.admin_accounts.superadmin_view', 'label' => 'View superadmin accounts'],
                'superadmin_manage' => ['permission' => 'admin.admin_accounts.superadmin_manage', 'label' => 'Manage superadmin accounts'],
                'superadmin_delete' => ['permission' => 'admin.admin_accounts.superadmin_delete', 'label' => 'Delete superadmin accounts'],
            ],
        ],
        'admin_scope' => [
            'section' => 'system',
            'label' => 'Admin Scope',
            'description' => 'Override regional restrictions and grant full admin data visibility.',
            'route_names' => [],
            'existing_authorization' => 'User::scopeManagedBy + Attendance::scopeManagedBy + AdminDashboardQueryService',
            'menu_location' => 'RBAC only',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'global' => ['permission' => 'admin.scope.global', 'label' => 'Global scope'],
            ],
        ],
        'settings' => [
            'section' => 'system',
            'label' => 'App Settings',
            'description' => 'View and manage system settings.',
            'route_names' => ['admin.settings'],
            'existing_authorization' => 'Gate:viewAdminSettings/manageSystemSettings/manageEnterpriseLicense',
            'menu_location' => 'Admin navigation > System > App Settings',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.settings.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.settings.manage', 'label' => 'Manage'],
                'license' => ['permission' => 'admin.settings.license', 'label' => 'Manage license'],
            ],
        ],
        'companies' => [
            'section' => 'system',
            'label' => 'Companies',
            'description' => 'Manage company, branch, store, or partner scopes for tenant isolation.',
            'route_names' => ['admin.companies'],
            'existing_authorization' => 'Gate:manageCompanies + MultiCompanyService',
            'menu_location' => 'Admin navigation > System > Companies',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.companies.manage', 'label' => 'Manage'],
            ],
        ],
        'operations_workspace' => [
            'section' => 'operations',
            'label' => 'Operations Workspace',
            'description' => 'Manage branches, clients, projects, tasks, and checklists.',
            'route_names' => ['admin.operations'],
            'existing_authorization' => 'Gate:viewOperationsWorkspace/manageOperationsWorkspace + OperationalWorkspaceService',
            'menu_location' => 'Admin navigation > Operations > Workspace',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.operations.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.operations.manage', 'label' => 'Manage'],
            ],
        ],
        'commercial_workspace' => [
            'section' => 'operations',
            'label' => 'Commercial Workspace',
            'description' => 'Manage products, stock movements, quotations, and invoices.',
            'route_names' => [
                'admin.commercial',
                'admin.commercial.quotations.pdf',
                'admin.commercial.invoices.pdf',
                'admin.commercial.vendor-bills.pdf',
            ],
            'existing_authorization' => 'Gate:viewCommercialWorkspace/manageCommercialWorkspace + CommercialWorkspaceService',
            'menu_location' => 'Admin navigation > Operations > Commercial',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.commercial.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.commercial.manage', 'label' => 'Manage'],
            ],
        ],
        'accounting_workspace' => [
            'section' => 'operations',
            'label' => 'Accounting Workspace',
            'description' => 'Manage chart of accounts and journal entries.',
            'route_names' => ['admin.accounting', 'admin.reports.accounting.export'],
            'existing_authorization' => 'Gate:viewAccountingWorkspace/manageAccountingWorkspace + AccountingWorkspaceService',
            'menu_location' => 'Admin navigation > Operations > Accounting',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.accounting.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.accounting.manage', 'label' => 'Manage'],
            ],
        ],
        'custom_forms' => [
            'section' => 'operations',
            'label' => 'Custom Forms',
            'description' => 'Build company-scoped dynamic forms and review submissions.',
            'route_names' => ['admin.custom-forms'],
            'existing_authorization' => 'Gate:viewCustomForms/manageCustomForms + CustomFormBuilderService',
            'menu_location' => 'Admin navigation > Operations > Forms',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.custom_forms.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.custom_forms.manage', 'label' => 'Manage'],
            ],
        ],
        'kpi_settings' => [
            'section' => 'system',
            'label' => 'KPI Settings',
            'description' => 'Manage KPI settings and weighting.',
            'route_names' => ['admin.settings.kpi'],
            'existing_authorization' => 'Gate:manageKpiSettings',
            'menu_location' => 'Admin navigation > System > KPI Settings',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'manage' => ['permission' => 'admin.kpi_settings.manage', 'label' => 'Manage'],
            ],
        ],
        'reports' => [
            'section' => 'system',
            'label' => 'Reports',
            'description' => 'Open operational HR and finance report exports.',
            'route_names' => ['admin.reports.index', 'admin.reports.leaves.export', 'admin.reports.schedules.export', 'admin.reports.overtime.export', 'admin.reports.payrolls.export'],
            'existing_authorization' => 'Gate:viewOperationalReports + module-specific export gates',
            'menu_location' => 'Admin navigation > System > Reports',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.reports.view', 'label' => 'View'],
                'export_leave' => ['permission' => 'admin.leave_approvals.approve', 'label' => 'Export leave requests'],
                'export_schedule' => ['permission' => 'admin.schedules.manage', 'label' => 'Export schedule roster'],
                'export_overtime' => ['permission' => 'admin.overtime.manage', 'label' => 'Export overtime'],
                'export_payroll' => ['permission' => 'admin.payroll.view', 'label' => 'Export payroll summary'],
            ],
        ],
        'import_export_users' => [
            'section' => 'system',
            'label' => 'Import/Export Users',
            'description' => 'Manage user import and export runs.',
            'route_names' => ['admin.import-export.users', 'admin.users.import', 'admin.users.export'],
            'existing_authorization' => 'Gate:accessUserImportExport/exportUsers',
            'menu_location' => 'Admin navigation > System > Import/Export Users',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.import_export_users.view', 'label' => 'View'],
                'import' => ['permission' => 'admin.import_export_users.import', 'label' => 'Import'],
                'export' => ['permission' => 'admin.import_export_users.export', 'label' => 'Export'],
            ],
        ],
        'import_export_attendances' => [
            'section' => 'system',
            'label' => 'Import/Export Attendance',
            'description' => 'Manage attendance import and export runs.',
            'route_names' => ['admin.import-export.attendances', 'admin.attendances.import', 'admin.attendances.export'],
            'existing_authorization' => 'Policy:Attendance@viewAdminAny + route can:importAttendances/exportAttendances',
            'menu_location' => 'Admin navigation > System > Import/Export Attendance',
            'surface' => 'admin',
            'enterprise' => true,
            'actions' => [
                'view' => ['permission' => 'admin.import_export_attendances.view', 'label' => 'View'],
                'import' => ['permission' => 'admin.import_export_attendances.import', 'label' => 'Import'],
                'export' => ['permission' => 'admin.import_export_attendances.export', 'label' => 'Export'],
            ],
        ],
        'activity_logs' => [
            'section' => 'system',
            'label' => 'Activity Logs',
            'description' => 'Review and export activity logs.',
            'route_names' => ['admin.activity-logs', 'admin.activity-logs.export'],
            'existing_authorization' => 'Gate:viewActivityLogs/exportActivityLogs',
            'menu_location' => 'Admin navigation > System > Activity Logs',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.activity_logs.view', 'label' => 'View'],
                'export' => ['permission' => 'admin.activity_logs.export', 'label' => 'Export'],
            ],
        ],
        'user_sessions' => [
            'section' => 'system',
            'label' => 'User Sessions',
            'description' => 'Disconnect active database sessions when users are blocked by another active device.',
            'route_names' => ['admin.user-sessions'],
            'existing_authorization' => 'Gate:manageUserSessions + UserSessionManagementService target checks',
            'menu_location' => 'Admin navigation > System > User Sessions',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.user_sessions.manage', 'label' => 'Manage'],
            ],
        ],
        'notifications' => [
            'section' => 'system',
            'label' => 'Notifications',
            'description' => 'Open the admin notification inbox and history.',
            'route_names' => ['admin.notifications'],
            'existing_authorization' => 'Gate:manageAdminNotifications',
            'menu_location' => 'Top bar > Notifications',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.notifications.view', 'label' => 'View'],
            ],
        ],
        'system_maintenance' => [
            'section' => 'system',
            'label' => 'System Maintenance',
            'description' => 'Review backup runs and perform maintenance and backup operations.',
            'route_names' => ['admin.system-maintenance'],
            'existing_authorization' => 'Policy:SystemBackupRun@viewAny/create/restore + Gate:manageSystemMaintenance',
            'menu_location' => 'Admin navigation > System > Maintenance',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'view' => ['permission' => 'admin.system_maintenance.view', 'label' => 'View'],
                'manage' => ['permission' => 'admin.system_maintenance.manage', 'label' => 'Manage'],
            ],
        ],
        'rbac' => [
            'section' => 'system',
            'label' => 'Roles & Permissions',
            'description' => 'Manage admin access roles and menu permissions.',
            'route_names' => ['admin.roles.permissions'],
            'existing_authorization' => 'Gate:manageRbac/assignRoles',
            'menu_location' => 'Admin navigation > System > Roles & Permissions',
            'surface' => 'admin',
            'enterprise' => false,
            'actions' => [
                'manage' => ['permission' => 'admin.rbac.manage', 'label' => 'Manage'],
                'assign' => ['permission' => 'admin.rbac.assign', 'label' => 'Assign roles'],
            ],
        ],
    ],

    'presets' => [
        'super_admin' => [
            'name' => 'Super Admin',
            'description' => 'Full access to all admin modules and role settings.',
            'permissions' => [
                '*' => ['*'],
            ],
            'is_system' => true,
            'is_super_admin' => true,
        ],
        'admin' => [
            'name' => 'Admin',
            'description' => 'Legacy-compatible operational admin access.',
            'permissions' => [
                'dashboard' => ['view'],
                'command_center' => ['view'],
                'attendances' => ['view', 'report', 'export'],
                'attendance_corrections' => ['view', 'approve'],
                'wfh_requests' => ['manage'],
                'leave_approvals' => ['approve'],
                'shift_swaps' => ['approve'],
                'overtime' => ['manage'],
                'schedules' => ['manage'],
                'holidays' => ['manage'],
                'announcements' => ['manage'],
                'reimbursements' => ['view', 'approve'],
                'employees' => ['view', 'manage', 'manage_status', 'approve_account_deletion'],
                'hr_checklists' => ['view', 'manage'],
                'operations_workspace' => ['view', 'manage'],
                'commercial_workspace' => ['view', 'manage'],
                'accounting_workspace' => ['view', 'manage'],
                'document_requests' => ['view', 'request', 'generate', 'templates', 'fulfill'],
                'appraisals' => ['view', 'manage'],
                'barcodes' => ['manage'],
                'divisions' => ['manage'],
                'job_titles' => ['manage'],
                'educations' => ['manage'],
                'shifts' => ['manage'],
                'leave_types' => ['manage'],
                'leave_entitlements' => ['manage'],
                'admin_accounts' => ['view'],
                'settings' => ['view'],
                'reports' => ['view'],
                'activity_logs' => ['view'],
                'user_sessions' => ['manage'],
                'notifications' => ['view'],
            ],
            'is_system' => true,
            'is_super_admin' => false,
        ],
        'hr' => [
            'name' => 'HR',
            'description' => 'Attendance, employee data, and operational HR workflows.',
            'permissions' => [
                'dashboard' => ['view'],
                'command_center' => ['view'],
                'attendances' => ['view', 'report', 'export'],
                'attendance_corrections' => ['view', 'approve'],
                'wfh_requests' => ['manage'],
                'leave_approvals' => ['approve'],
                'shift_swaps' => ['approve'],
                'overtime' => ['manage'],
                'schedules' => ['manage'],
                'holidays' => ['manage'],
                'announcements' => ['manage'],
                'employees' => ['view', 'manage', 'manage_status', 'approve_account_deletion'],
                'hr_checklists' => ['view', 'manage'],
                'document_requests' => ['view', 'request', 'generate', 'templates', 'fulfill'],
                'appraisals' => ['view', 'manage'],
                'divisions' => ['manage'],
                'job_titles' => ['manage'],
                'educations' => ['manage'],
                'shifts' => ['manage'],
                'leave_types' => ['manage'],
                'leave_entitlements' => ['manage'],
                'reports' => ['view'],
                'notifications' => ['view'],
            ],
            'is_system' => true,
            'is_super_admin' => false,
        ],
        'finance' => [
            'name' => 'Finance',
            'description' => 'Finance workflows for reimbursements, cash advances, and payroll.',
            'permissions' => [
                'dashboard' => ['view'],
                'command_center' => ['view'],
                'reimbursements' => ['view', 'approve'],
                'cash_advances' => ['manage'],
                'payroll' => ['view'],
                'payroll_settings' => ['manage'],
                'commercial_workspace' => ['view', 'manage'],
                'accounting_workspace' => ['view', 'manage'],
                'reports' => ['view'],
                'activity_logs' => ['view'],
                'notifications' => ['view'],
            ],
            'is_system' => true,
            'is_super_admin' => false,
        ],
        'it' => [
            'name' => 'IT',
            'description' => 'System tools, imports, settings, and audit access.',
            'permissions' => [
                'dashboard' => ['view'],
                'barcodes' => ['manage'],
                'settings' => ['view', 'manage'],
                'import_export_users' => ['view', 'import', 'export'],
                'import_export_attendances' => ['view', 'import', 'export'],
                'activity_logs' => ['view', 'export'],
                'user_sessions' => ['manage'],
                'notifications' => ['view'],
                'system_maintenance' => ['view', 'manage'],
                'rbac' => ['assign'],
            ],
            'is_system' => true,
            'is_super_admin' => false,
        ],
    ],
];
