<?php

declare(strict_types=1);

$legacyInlineSvgFiles = [
    'resources/views/attendances/history.blade.php',
    'resources/views/attendances/scan.blade.php',
    'resources/views/auth/forgot-password.blade.php',
    'resources/views/auth/login.blade.php',
    'resources/views/auth/reset-password.blade.php',
    'resources/views/layouts/app.blade.php',
    'resources/views/livewire/admin/analytics-dashboard.blade.php',
    'resources/views/livewire/admin/announcement-manager.blade.php',
    'resources/views/livewire/admin/attendance.blade.php',
    'resources/views/livewire/admin/holiday-manager.blade.php',
    'resources/views/livewire/admin/import-export/user.blade.php',
    'resources/views/livewire/admin/leave-approval.blade.php',
    'resources/views/livewire/admin/master-data/admin.blade.php',
    'resources/views/livewire/admin/master-data/division.blade.php',
    'resources/views/livewire/admin/master-data/education.blade.php',
    'resources/views/livewire/admin/master-data/job-title.blade.php',
    'resources/views/livewire/admin/master-data/shift.blade.php',
    'resources/views/livewire/admin/notifications-page.blade.php',
    'resources/views/livewire/admin/overtime-manager.blade.php',
    'resources/views/livewire/admin/payroll-manager.blade.php',
    'resources/views/livewire/admin/payroll-settings.blade.php',
    'resources/views/livewire/admin/reimbursement-manager.blade.php',
    'resources/views/livewire/admin/system-maintenance.blade.php',
    'resources/views/livewire/user/attendance-correction-page.blade.php',
    'resources/views/livewire/user/overtime-request.blade.php',
    'resources/views/livewire/user/team-approvals-history.blade.php',
    'resources/views/livewire/user/upcoming-events-widget.blade.php',
    'resources/views/profile/logout-other-browser-sessions-form.blade.php',
    'resources/views/profile/update-profile-information-form.blade.php',
];

$legacyTableFiles = [
    'resources/views/admin/operational-health.blade.php',
    'resources/views/livewire/admin/activity-logs.blade.php',
    'resources/views/livewire/admin/announcement-manager.blade.php',
    'resources/views/livewire/admin/appraisal-manager.blade.php',
    'resources/views/livewire/admin/asset-manager.blade.php',
    'resources/views/livewire/admin/attendance-correction-manager.blade.php',
    'resources/views/livewire/admin/attendance.blade.php',
    'resources/views/livewire/admin/dashboard.blade.php',
    'resources/views/livewire/admin/document-template-library.blade.php',
    'resources/views/livewire/admin/employee-document-request-manager.blade.php',
    'resources/views/livewire/admin/employees.blade.php',
    'resources/views/livewire/admin/holiday-manager.blade.php',
    'resources/views/livewire/admin/import-export/attendance.blade.php',
    'resources/views/livewire/admin/import-export/user.blade.php',
    'resources/views/livewire/admin/leave-approval.blade.php',
    'resources/views/livewire/admin/master-data/admin.blade.php',
    'resources/views/livewire/admin/master-data/division.blade.php',
    'resources/views/livewire/admin/master-data/education.blade.php',
    'resources/views/livewire/admin/master-data/job-title.blade.php',
    'resources/views/livewire/admin/master-data/leave-types.blade.php',
    'resources/views/livewire/admin/master-data/shift.blade.php',
    'resources/views/livewire/admin/payroll-manager.blade.php',
    'resources/views/livewire/admin/payroll-settings.blade.php',
    'resources/views/livewire/admin/reimbursement-manager.blade.php',
    'resources/views/livewire/admin/settings/kpi-settings.blade.php',
    'resources/views/livewire/shared/finance/cash-advance-manager-content.blade.php',
    'resources/views/livewire/user/attendance-correction-page.blade.php',
    'resources/views/livewire/user/employee-document-request-page.blade.php',
    'resources/views/livewire/user/partials/team-attendance-corrections-history.blade.php',
    'resources/views/livewire/user/partials/team-attendance-corrections-pending.blade.php',
    'resources/views/livewire/user/partials/team-shift-swaps-history.blade.php',
    'resources/views/livewire/user/partials/team-shift-swaps-pending.blade.php',
    'resources/views/livewire/user/shift-swap-request-page.blade.php',
    'resources/views/livewire/user/team-approvals-history.blade.php',
    'resources/views/livewire/user/team-approvals.blade.php',
];

$legacyWarningFindings = [
    ['app/Livewire/Forms/UserForm.php', 'hardcoded_ui_text', 219, 'Possible hardcoded Livewire UI text: "Demo user password cannot be changed."'],
    ['lang/en.json', 'translation_file_drift', 1, 'Translation file drift detected: 194 key(s) exist in lang/id.json but not in lang/en.json. Blocking enforcement currently targets UI-used literal keys.'],
    ['resources/views/admin/attendances/report.blade.php', 'hardcoded_ui_text', 235, 'Possible hardcoded UI text: "Tidak ada data"'],
    ['resources/views/auth/forgot-password.blade.php', 'missing_form_label', 38, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/login.blade.php', 'missing_form_label', 35, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/login.blade.php', 'missing_form_label', 56, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/register.blade.php', 'icon_only_button_accessibility', 271, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/auth/reset-password.blade.php', 'missing_form_label', 40, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/reset-password.blade.php', 'missing_form_label', 59, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/auth/reset-password.blade.php', 'missing_form_label', 78, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/components/branding/application-logo.blade.php', 'hardcoded_ui_text', 1, 'Possible hardcoded UI attribute text: "Logo"'],
    ['resources/views/components/branding/application-mark.blade.php', 'hardcoded_ui_text', 1, 'Possible hardcoded UI attribute text: "Logo"'],
    ['resources/views/components/branding/authentication-card-logo.blade.php', 'hardcoded_ui_text', 1, 'Possible hardcoded UI attribute text: "Logo"'],
    ['resources/views/components/navigation/theme-toggle.blade.php', 'missing_form_label', 2, 'Possible missing label or aria-label for <input>.'],
    ['resources/views/components/shared/attendance-detail-modal.blade.php', 'hardcoded_ui_text', 107, 'Possible hardcoded UI attribute text: "Attachment"'],
    ['resources/views/components/shared/feature-lock-modal.blade.php', 'icon_only_button_accessibility', 174, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/home-actions-card.blade.php', 'icon_only_button_accessibility', 67, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/home-actions-card.blade.php', 'icon_only_button_accessibility', 156, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/location-card.blade.php', 'icon_only_button_accessibility', 23, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/scanner-card.blade.php', 'icon_only_button_accessibility', 14, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/components/user/tom-select-user.blade.php', 'missing_form_label', 148, 'Possible missing label or aria-label for <select>.'],
    ['resources/views/layouts/guest.blade.php', 'hardcoded_ui_text', 61, 'Possible hardcoded UI text: "ID"'],
    ['resources/views/layouts/guest.blade.php', 'hardcoded_ui_text', 62, 'Possible hardcoded UI text: "EN"'],
    ['resources/views/livewire/admin/activity-logs.blade.php', 'mobile_layout_red_flag', 102, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/announcement-manager.blade.php', 'mobile_layout_red_flag', 63, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'mobile_layout_red_flag', 64, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'mobile_layout_red_flag', 98, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/appraisal-manager.blade.php', 'hardcoded_ui_text', 502, 'Possible hardcoded UI attribute text: "https://meet.google.com/..."'],
    ['resources/views/livewire/admin/dashboard.blade.php', 'mobile_layout_red_flag', 672, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/dashboard.blade.php', 'mobile_layout_red_flag', 819, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/employee-document-request-manager.blade.php', 'mobile_layout_red_flag', 36, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/employees.blade.php', 'mobile_layout_red_flag', 101, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 524, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 545, 'Possible hardcoded UI attribute text: "e.g. 25.000"'],
    ['resources/views/livewire/admin/employees.blade.php', 'hardcoded_ui_text', 735, 'Possible hardcoded UI attribute text: "e.g. 5.000.000"'],
    ['resources/views/livewire/admin/holiday-manager.blade.php', 'mobile_layout_red_flag', 52, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'icon_only_button_accessibility', 28, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'icon_only_button_accessibility', 46, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'icon_only_button_accessibility', 143, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/attendance.blade.php', 'mobile_layout_red_flag', 425, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/import-export/user.blade.php', 'icon_only_button_accessibility', 28, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/user.blade.php', 'icon_only_button_accessibility', 46, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/admin/import-export/user.blade.php', 'mobile_layout_red_flag', 364, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/leave-approval.blade.php', 'mobile_layout_red_flag', 48, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/admin.blade.php', 'mobile_layout_red_flag', 152, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/division.blade.php', 'mobile_layout_red_flag', 57, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/education.blade.php', 'mobile_layout_red_flag', 58, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/job-title.blade.php', 'mobile_layout_red_flag', 72, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/leave-types.blade.php', 'mobile_layout_red_flag', 37, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/master-data/shift.blade.php', 'mobile_layout_red_flag', 81, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/payroll-manager.blade.php', 'mobile_layout_red_flag', 87, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/payroll-settings.blade.php', 'mobile_layout_red_flag', 60, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/payroll-settings.blade.php', 'hardcoded_ui_text', 219, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/admin/reimbursement-manager.blade.php', 'mobile_layout_red_flag', 30, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/admin/schedule-component.blade.php', 'mobile_layout_red_flag', 34, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/schedule-component.blade.php', 'mobile_layout_red_flag', 44, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/admin/settings.blade.php', 'icon_only_button_accessibility', 120, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/shared/finance/cash-advance-manager-content.blade.php', 'mobile_layout_red_flag', 27, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/shared/finance/cash-advance-manager-content.blade.php', 'mobile_layout_red_flag', 231, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/shared/notifications-dropdown.blade.php', 'icon_only_button_accessibility', 5, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/attendance-correction-page.blade.php', 'icon_only_button_accessibility', 16, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/attendance-correction-page.blade.php', 'mobile_layout_red_flag', 54, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/attendance-history.blade.php', 'mobile_layout_red_flag', 36, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/user/attendance-history.blade.php', 'mobile_layout_red_flag', 45, 'High default grid column count may be too dense for mobile.'],
    ['resources/views/livewire/user/attendance-history.blade.php', 'hardcoded_ui_text', 123, 'Possible hardcoded UI text: "H"'],
    ['resources/views/livewire/user/employee-document-request-page.blade.php', 'icon_only_button_accessibility', 15, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/face-enrollment.blade.php', 'icon_only_button_accessibility', 26, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/face-enrollment.blade.php', 'icon_only_button_accessibility', 33, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/face-enrollment.blade.php', 'icon_only_button_accessibility', 40, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'icon_only_button_accessibility', 14, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'icon_only_button_accessibility', 25, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'hardcoded_ui_text', 50, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/finance/my-cash-advances.blade.php', 'hardcoded_ui_text', 188, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/home-attendance-status.blade.php', 'icon_only_button_accessibility', 61, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-assets.blade.php', 'icon_only_button_accessibility', 208, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'icon_only_button_accessibility', 16, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'icon_only_button_accessibility', 21, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'hardcoded_ui_text', 89, 'Possible hardcoded UI text: "Rp *********"'],
    ['resources/views/livewire/user/my-payslips.blade.php', 'icon_only_button_accessibility', 91, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/overtime-request.blade.php', 'icon_only_button_accessibility', 16, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/overtime-request.blade.php', 'icon_only_button_accessibility', 21, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/partials/team-attendance-corrections-history.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/partials/team-attendance-corrections-pending.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/partials/team-shift-swaps-history.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/partials/team-shift-swaps-pending.blade.php', 'mobile_layout_red_flag', 2, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'icon_only_button_accessibility', 18, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'icon_only_button_accessibility', 24, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'hardcoded_ui_text', 78, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/reimbursement-page.blade.php', 'hardcoded_ui_text', 248, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/scan.blade.php', 'icon_only_button_accessibility', 402, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/scan.blade.php', 'icon_only_button_accessibility', 445, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/shift-swap-request-page.blade.php', 'icon_only_button_accessibility', 12, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/livewire/user/shift-swap-request-page.blade.php', 'mobile_layout_red_flag', 30, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 63, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 240, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 406, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'mobile_layout_red_flag', 523, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals-history.blade.php', 'hardcoded_ui_text', 601, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 79, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 292, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 505, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'hardcoded_ui_text', 626, 'Possible hardcoded UI text: "SPL"'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'mobile_layout_red_flag', 687, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/livewire/user/team-approvals.blade.php', 'hardcoded_ui_text', 810, 'Possible hardcoded UI text: "Rp"'],
    ['resources/views/navigation-menu.blade.php', 'icon_only_button_accessibility', 327, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/navigation-menu.blade.php', 'icon_only_button_accessibility', 405, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/profile/admin-show.blade.php', 'hardcoded_ui_text', 61, 'Possible hardcoded UI text: "ID"'],
    ['resources/views/profile/admin-show.blade.php', 'hardcoded_ui_text', 62, 'Possible hardcoded UI text: "EN"'],
    ['resources/views/profile/show.blade.php', 'hardcoded_ui_text', 67, 'Possible hardcoded UI text: "ID"'],
    ['resources/views/profile/show.blade.php', 'hardcoded_ui_text', 68, 'Possible hardcoded UI text: "EN"'],
    ['resources/views/profile/two-factor-authentication-form.blade.php', 'mobile_layout_red_flag', 45, 'overflow-x-auto can hide underlying mobile layout issues.'],
    ['resources/views/profile/update-profile-information-form.blade.php', 'icon_only_button_accessibility', 91, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/profile/update-profile-information-form.blade.php', 'icon_only_button_accessibility', 139, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/profile/update-profile-information-form.blade.php', 'icon_only_button_accessibility', 188, 'Possible icon-only button without aria-label or visible text.'],
    ['resources/views/static/pwa.blade.php', 'hardcoded_ui_text', 9, 'Possible hardcoded UI text: "PasPapan"'],
    ['resources/views/static/pwa.blade.php', 'hardcoded_ui_text', 19, 'Possible hardcoded UI text: "PasPapan"'],
];

return array_merge(
    array_map(
        static fn (string $file): array => [
            'file' => $file,
            'rule' => 'raw_inline_svg',
            'reason' => 'Legacy inline SVG pending Heroicons migration.',
        ],
        $legacyInlineSvgFiles,
    ),
    array_map(
        static fn (string $file): array => [
            'file' => $file,
            'rule' => 'table_usage',
            'reason' => 'Legacy table layout pending card-first mobile migration.',
        ],
        $legacyTableFiles,
    ),
    array_map(
        static fn (array $finding): array => [
            'file' => $finding[0],
            'rule' => $finding[1],
            'key' => $finding[2].'|'.$finding[3],
            'reason' => 'Existing warning baseline; keep new UI warnings visible while legacy cleanup is tracked separately.',
        ],
        $legacyWarningFindings,
    ),
);
